[project]
name = "orchestrator"
version = "0.1.0"
description = "Demonstration of orchestrator pattern"
requires-python = ">=3.11, <4.0"
dependencies = [
    "acp-sdk",
    "beeai-framework>=0.1.17",
    "pydantic-settings>=2.9.0",
]

[tool.uv.sources]
acp-sdk = { workspace = true }
