[tool.uv.workspace]
members = ["python", "examples/python/*"]

[tool.ruff]
lint.select = [
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    "UP", # pyupgrade
    "I", # isort
    "B", # bugbear
    "ANN", # annotations
    "N", # pep8-naming
    "C4", # Comprehensions
    "DTZ", # DatetimeZ
    "Q", # Quotes
    "SIM", # Simplify
    "RUF", # Ruff
    "TID", # tidy-imports
    "ASYNC", # async
]
lint.ignore = ["ANN401", "B904"]
lint.fixable = ["ALL"]
lint.unfixable = []
force-exclude = true
line-length = 120

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.flake8-tidy-imports]
# Disallow all relative imports, "parents" | "all"
ban-relative-imports = "all"

[tool.uv]
dev-dependencies = [
    "autodoc-pydantic>=2.2.0",
    "furo>=2024.8.6",
    "pyright>=1.1.391",
    "pytest>=8.3.4",
    "pytest-asyncio>=0.26.0",
    "ruff>=0.8.5",
    "sphinx>=8.2.3",
    "sphinx-toolbox>=3.9.0",
]
