[project]
name = "crewai-song-writer"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11, <4.0"
dependencies = [
    "acp-sdk",
    "crewai[tools]>=0.95.0",
]

[tool.uv.sources]
acp-sdk = { workspace = true }
